// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"changelog.mdx": () => import("../content/docs/changelog.mdx?collection=docs"), "common-tasks.mdx": () => import("../content/docs/common-tasks.mdx?collection=docs"), "errors.mdx": () => import("../content/docs/errors.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "operations.mdx": () => import("../content/docs/operations.mdx?collection=docs"), "platforms.mdx": () => import("../content/docs/platforms.mdx?collection=docs"), "support.mdx": () => import("../content/docs/support.mdx?collection=docs"), "api-reference/index.mdx": () => import("../content/docs/api-reference/index.mdx?collection=docs"), "api-reference/jobs.mdx": () => import("../content/docs/api-reference/jobs.mdx?collection=docs"), "api-reference/uploads.mdx": () => import("../content/docs/api-reference/uploads.mdx?collection=docs"), "api-reference/utils.mdx": () => import("../content/docs/api-reference/utils.mdx?collection=docs"), "api-reference/webhooks.mdx": () => import("../content/docs/api-reference/webhooks.mdx?collection=docs"), "architecture/index.mdx": () => import("../content/docs/architecture/index.mdx?collection=docs"), "get-started/authentication.mdx": () => import("../content/docs/get-started/authentication.mdx?collection=docs"), "get-started/concepts.mdx": () => import("../content/docs/get-started/concepts.mdx?collection=docs"), "get-started/quickstart.mdx": () => import("../content/docs/get-started/quickstart.mdx?collection=docs"), "webhooks/delivery.mdx": () => import("../content/docs/webhooks/delivery.mdx?collection=docs"), "webhooks/event-catalog.mdx": () => import("../content/docs/webhooks/event-catalog.mdx?collection=docs"), "webhooks/index.mdx": () => import("../content/docs/webhooks/index.mdx?collection=docs"), "webhooks/payload.mdx": () => import("../content/docs/webhooks/payload.mdx?collection=docs"), "webhooks/security.mdx": () => import("../content/docs/webhooks/security.mdx?collection=docs"), "webhooks/subscriptions.mdx": () => import("../content/docs/webhooks/subscriptions.mdx?collection=docs"), "webhooks/testing.mdx": () => import("../content/docs/webhooks/testing.mdx?collection=docs"), }),
};
export default browserCollections;