"""make source_uri nullable on the job table

Revision ID: 99722ec6b2d6
Revises: d61ac962ddf1
Create Date: 2026-08-14 22:27:18.802446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99722ec6b2d6'
down_revision: Union[str, Sequence[str], None] = 'd61ac962ddf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'source_uri',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'source_uri',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
