"""add key prefix column to api_key table

Revision ID: a2a650a06036
Revises: 
Create Date: 2026-06-10 18:43:40.852391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a2a650a06036'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key_prefix', sa.String(length=16), nullable=False))
    op.add_column('api_keys', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('api_keys', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.drop_column('api_keys', 'revoked_at')
    op.drop_column('api_keys', 'prefix')
    op.drop_column('api_keys', 'scopes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('scopes', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=False))
    op.add_column('api_keys', sa.Column('prefix', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('api_keys', sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.alter_column('api_keys', 'key_hash',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('api_keys', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('api_keys', 'status')
    op.drop_column('api_keys', 'key_prefix')
    # ### end Alembic commands ###
