"""add_source_metadata_parent_job_id_and_error_columns_to_jobs_table

Revision ID: bcaf878d49ec
Revises: 16c0b99efaab
Create Date: 2026-07-04 11:14:19.878117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcaf878d49ec'
down_revision: Union[str, Sequence[str], None] = '16c0b99efaab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('jobs', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('parent_job_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_parent_job_id'), 'jobs', ['parent_job_id'], unique=False)
    op.create_foreign_key(op.f('fk_jobs_parent_job_id_jobs'), 'jobs', 'jobs', ['parent_job_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_jobs_parent_job_id_jobs'), 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_parent_job_id'), table_name='jobs')
    op.drop_column('jobs', 'parent_job_id')
    op.drop_column('jobs', 'error')
    op.drop_column('jobs', 'source_metadata')
    # ### end Alembic commands ###
