"""selection_columns_to_jobs_table

Revision ID: c39e8cb08d5e
Revises: ea3ad4859918
Create Date: 2026-07-04 22:43:34.815161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c39e8cb08d5e'
down_revision: Union[str, Sequence[str], None] = 'ea3ad4859918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('selection', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'selection')
    # ### end Alembic commands ###
