"""add retry count, max retries column to Job table

Revision ID: d61ac962ddf1
Revises: 1d9954616d8a
Create Date: 2026-08-09 21:26:28.514301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd61ac962ddf1'
down_revision: Union[str, Sequence[str], None] = '1d9954616d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('jobs', sa.Column('max_retries', sa.Integer(), nullable=False, server_default='3'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'max_retries')
    op.drop_column('jobs', 'retry_count')
    # ### end Alembic commands ###
