"""entry_index_columns_to_jobs_table

Revision ID: ea3ad4859918
Revises: bcaf878d49ec
Create Date: 2026-07-04 12:15:22.526515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea3ad4859918'
down_revision: Union[str, Sequence[str], None] = 'bcaf878d49ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('playlist_entry_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'playlist_entry_index')
    # ### end Alembic commands ###
